### PR TITLE
more error handling

### PR DESCRIPTION
**Pull request by karlkeefer**
`cannot find property ask of undefined` seems to come mostly from getLatestPrices jumping to the surface

### CODE REVIEW

**Comment by taariq** [comment]
Lord. Was that like nearly 5 years later!

**Comment by porkchop** [comment]
Man I've been waiting so long for this one to close

**Comment by taariq** [comment]
@porkchop you had me rolling on the floor laughing! I woke the baby!

**Comment by porkchop** [comment]
hahaha give her a kiss for me @taariq !!!

**Comment by karlkeefer** [comment]
I started rewriting the whole stack in go so this bug is irrelevant now :trollface:

**Comment by porkchop** [comment]
solid pivot @karlkeefer

**Comment by taariq** [comment]
don't encourage him @porkchop! Next thing he's going to have a React Mobile front-end to that Go backend!

**Pull request closed without merging**
